#!/bin/bash

./bash/plainedit.sh --path $(pwd) $@

echo "$1 $2"
if [[ "$1" != "" ]]; then
    [[ "$2" == "" ]] && pandoc -f markdown "$1/out.md" > index.html
    [[ "$2" != "" ]] && pandoc -f markdown "$2" > index.html
    firefox index.html
fi